kind: pipeline
type: docker
name: Build Advent of Qode

steps:

- name: build-backend
  image: plugins/docker
  settings:
    repo: jclement/aoc-backend
    dry_run: true
    tags: 
      - ${DRONE_COMMIT_BRANCH}
    dockerfile: backend/Dockerfile
    context: backend

- name: build-frontend
  image: plugins/docker
  settings:
    repo: jclement/aoc-frontend
    dry_run: true
    tags: 
      - ${DRONE_COMMIT_BRANCH}
    dockerfile: frontend/Dockerfile
    context: frontend

- name: publish-backend
  image: plugins/docker
  when:
   branch:
    - master
   event:
    - push
  settings:
    repo: jclement/aoc-backend
    dry_run: false
    tags: 
      - ${DRONE_COMMIT_BRANCH}
    dockerfile: backend/Dockerfile
    context: backend
    username: jclement
    password:
      from_secret: DOCKERHUB_KEY

- name: publish-frontend
  image: plugins/docker
  when:
   branch:
    - master
   event:
    - push
  settings:
    repo: jclement/aoc-frontend
    dry_run: false
    tags: 
      - ${DRONE_COMMIT_BRANCH}
    dockerfile: frontend/Dockerfile
    context: frontend
    username: jclement
    password:
      from_secret: DOCKERHUB_KEY
