kind: pipeline
type: docker
name: Build Advent of Qode

steps:

- name: build-backend
  image: plugins/docker
  settings:
    repo: jclement/aoc-backend
    dry_run: true
    tags:
     - latest
    dockerfile: backend/Dockerfile
    context: backend
    username: jclement
    password:
      from_secret: DOCKERHUB_KEY

- name: publish-backend
  image: plugins/docker
  settings:
    repo: jclement/aoc-backend
    tags:
     - latest
    dockerfile: backend/Dockerfile
    context: backend
    username: jclement
    password:
      from_secret: DOCKERHUB_KEY
  when:
   target: production