kind: pipeline
type: docker
name: Build Advent of Qode

steps:

- name: build-backend
  image: plugins/docker
  settings:
    repo: jclement/aoc-backend
    tags:
     - ${DRONE_BRANCH}
    dockerfile: backend/Dockerfile
    context: backend
    username: jclement
    password:
      from_secret: DOCKERHUB_KEY
  when:
   event:
    - pr

- name: publish-backend
  image: plugins/docker
  settings:
    repo: jclement/aoc-backend
    tags:
     - ${DRONE_BRANCH}
    dockerfile: backend/Dockerfile
    context: backend
    username: jclement
    password:
      from_secret: DOCKERHUB_KEY
  when:
   event:
    - push
  
