kind: pipeline
type: docker
name: default
steps:
- name: publish-frontend
  image: plugins/docker
  settings:
    repo: registry.erraticbits.ca/aoc-frontend
    tags: 
      - ${DRONE_COMMIT_BRANCH}
    dockerfile: frontend/Dockerfile
    registry: registry.erraticbits.ca
    username: jsc
    password:
      from_secret: DOCKER_SECRET
- name: publish-backend
  image: plugins/docker
  settings:
    repo: registry.erraticbits.ca/aoc-backend
    tags: 
      - ${DRONE_COMMIT_BRANCH}
    dockerfile: frontend/Dockerfile
    registry: registry.erraticbits.ca
    username: jsc
    password:
      from_secret: DOCKER_SECRET
