kind: pipeline
type: docker
name: Build Advent of Qode

steps:

- name: publish-backend
  image: plugins/docker
  settings:
    repo: jclement/aoc-backend
    tags:
     - "${DRONE_BRANCH}_${DRONE_BUILD_NUMBER}"
     - "${DRONE_BRANCH}"
    dockerfile: backend/Dockerfile
    context: backend
    username: jclement
    password:
      from_secret: DOCKERHUB_KEY
  when:
    branch: ["master"]

- name: publish-frontend
  image: plugins/docker
  settings:
    repo: jclement/aoc-frontend
    tags:
     - "${DRONE_BRANCH}_${DRONE_BUILD_NUMBER}"
     - "${DRONE_BRANCH}"
    dockerfile: frontend/Dockerfile
    context: frontend
    username: jclement
    password:
      from_secret: DOCKERHUB_KEY
  when:
    branch: ["master"]
    #event: [push]
