kind: pipeline
type: docker
name: Build Advent of Qode

steps:

- name: build-backend
  image: plugins/docker
  settings:
    repo: jclement/aoc-backend
    dryrun: true
    tags:
     - ${DRONE_BRANCH}
    dockerfile: backend/Dockerfile
    context: backend

- name: public-backend
  image: plugins/docker
  settings:
    repo: jclement/aoc-backend
    username: jclement
    password:
      from_secret: DOCKERHUB_KEY

