kind: pipeline
type: docker
name: Build Advent of Qode

steps:

- name: build-images
  image: plugins/docker
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  commands:
    - cd backend #&& docker build . -t jclement/aoc-backend:${DRONE_BRANCH}-${DRONE_BUILD_NUMBER} -t jclement/aoc-backend:${DRONE_BRANCH}-latest

#- name: publish
#  image: docker
#  volumes:
#    - "/var/run/docker.sock:/var/run/docker.sock"
#  environment:
#    DOCKERHUB_KEY:
#      from_secret: DOCKERHUB_KEY
#  commands:
#    - docker login jclement -p ${DOCKERHUB_KEY}
    #- docker push jclement/aoc-backend:${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}
    #- docker push jclement/aoc-backend:${DRONE_BRANCH}-latest
#  when:
#   status: [success]
