kind: pipeline
type: docker
name: Build Advent of Qode

steps:

- name: publish-backend
  image: plugins/docker
  settings:
    repo: jclement/aoc-backend
    tags:
     - "${DRONE_BRANCH}_${DRONE_COMMIT}"
    dockerfile: backend/Dockerfile
    context: backend
    username: jclement
    password:
      from_secret: DOCKERHUB_KEY
  when:
    branch: ["master"]

- name: publish-frontend
  image: plugins/docker
  settings:
    repo: jclement/aoc-frontend
    tags:
     - "${DRONE_BRANCH}_${DRONE_COMMIT}"
    dockerfile: frontend/Dockerfile
    context: frontend
    username: jclement
    password:
      from_secret: DOCKERHUB_KEY
  when:
    branch: ["master"]

- name: deploy
    image: williamyeh/ansible:ubuntu16.04
    commands:
      - echo "${DRONE_BRANCH}_${DRONE_COMMIT}"
    when:
      branch: ["master"]
      event: [push]