kind: pipeline
type: docker
name: Build Advent of Qode
when:
  branch: 
  - master
  - staging
  event: push

steps:
- name: publish-backend
  image: plugins/docker
  settings:
    repo: jclement/aoc-backend
    tags:
     - ${DRONE_BRANCH}
    dockerfile: backend/Dockerfile
    context: backend
    username: jclement
    password:
      from_secret: DOCKERHUB_KEY
