kind: pipeline
type: docker
name: default

steps:

- name: build-backend
  image: plugins/docker
  settings:
    repo: jclement/aoc-backend
    dry_run: true
    tags: 
      - ${DRONE_COMMIT_BRANCH}
    dockerfile: backend/Dockerfile
    context: backend

- name: publish-backend
  image: plugins/docker
  settings:
    repo: jclement/aoc-backend
    dry_run: false
    tags: 
      - ${DRONE_COMMIT_BRANCH}
    dockerfile: backend/Dockerfile
    context: backend
    username: jclement
    password:
      from_secret: DOCKERHUB_KEY

#- name: build-frontend
#  image: plugins/docker
#  settings:
#    dry_run: true
#    repo: jclement/aoc-frontend
#    tags: 
#      - ${DRONE_COMMIT_BRANCH}
#    dockerfile: frontend/Dockerfile
#    context: frontned

