kind: pipeline
type: docker
name: default

steps:

- name: build-backend
  image: plugins/docker
  settings:
    repo: jclement/aoc-backend
    tags: 
      - ${DRONE_COMMIT_BRANCH}
    dockerfile: backend/Dockerfile
    context: backend

#- name: publish-frontend
#  image: plugins/docker
#  settings:
#    repo: jclement/aoc-frontend
#    username: jclement
#    password:
#      from_secret: DOCKERHUB_KEY
#  when:
#   branch:
#    -master
#    -staging
#   event: 
#    - push

- name: publish-backend
  image: plugins/docker
  settings:
    repo: jclement/aoc-backend
    tags: 
      - ${DRONE_COMMIT_BRANCH}
    dockerfile: backend/Dockerfile
    context: backend
    username: jclement
    password:
      from_secret: DOCKERHUB_KEY
  when:
   branch:
    -master
    -staging
   event: 
    - push
