kind: pipeline
type: docker
name: Build Advent of Qode

steps:

- name: build-backend
  image: plugins/docker
  settings:
    repo: jclement/aoc-backend
    dry_run: true
    tags:
     - ${DRONE_BRANCH}
    dockerfile: backend/Dockerfile
    context: backend
    username: jclement
    password:
      from_secret: DOCKERHUB_KEY
  when:
    branch: 
    - master
    - staging
    event: pull_request

- name: build-frontend
  image: plugins/docker
  settings:
    repo: jclement/aoc-frontend
    dry_run: true
    tags:
     - ${DRONE_BRANCH}
    dockerfile: frontend/Dockerfile
    context: frontend
    username: jclement
    password:
      from_secret: DOCKERHUB_KEY
  when:
    branch: 
    - master
    - staging
    event: pull_request

- name: publish-backend
  image: plugins/docker
  settings:
    repo: jclement/aoc-backend
    tags:
     - ${DRONE_BRANCH}
    dockerfile: backend/Dockerfile
    context: backend
    username: jclement
    password:
      from_secret: DOCKERHUB_KEY
  when:
    branch: 
    - master
    - staging
    event: push

- name: publish-frontend
  image: plugins/docker
  settings:
    repo: jclement/aoc-frontend
    tags:
     - ${DRONE_BRANCH}
    dockerfile: frontend/Dockerfile
    context: frontend
    username: jclement
    password:
      from_secret: DOCKERHUB_KEY
  when:
    branch: 
    - master
    - staging
    event: push
